config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'restaurants#index'

  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :cuisine, presence: true
  validates :name, format: { with: /\A[A-Z]/, message: "Has to start with capital letter" }
  validates :cuisine, length: { minimum: 3 }

  has_many :reviews
  belongs_to :user

  def average_rating
    return "N/A" if reviews.none?
    reviews.average(:rating)
    # more convoluted
    # reviews.inject(0) { |sum, review| (sum + review.rating) / reviews.count }
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @restaurants = Restaurant.all
    @review = Review.new
  end

  def new # get function
    @restaurant = Restaurant.new
  end

  def create # post function
    # Restaurant.create(params[:name]) - no longer allowed in Rails 4 due to
    # security risk
    @restaurant = Restaurant.create restaurant_params
    @restaurant.user = current_user

    if @restaurant.save
      redirect_to '/restaurants'
    else
      # if there is an error in creating a restaurant
      render 'new'
    end

  end

  def edit # get function
    @restaurant = Restaurant.find params[:id]
    # .find (ActiveRecord) is the same as .get in DataMapper
  end

  def update # post function
    @restaurant = Restaurant.find params[:id]
    @restaurant.update restaurant_params
    # this would work: @restaurant.update {name: "Kentucky Fried Chicken"}
    # since params are sent via hashes
    # can check this by trying to raise an error: raise "hello"

    # in console log, would be able to do:
    # @restaurant = Restaurant.first
    # @restaurant.update(name: "kentucky fried chicken")
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = current_user.restaurants.find params[:id]
    @restaurant.destroy
    flash[:notice] = "Successfully deleted #{@restaurant.name}"

    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "You cannot delete it as it's not your restaurant"
    ensure
      redirect_to '/restaurants'
  end

  private 

  def restaurant_params
    #explicitly allow this input field to be submitted
    params.require(:restaurant).permit(:name, :cuisine)
    # or params[:restaurant].permit(:name, :cuisine)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find params[:restaurant_id]
    @review = @restaurant.reviews.create review_params
    # flash[:notice] = "Your review has been added"

    # display the json formated (as defined in views>create.json.jbuilder) 
    # of the new review
    # render json: @review
    redirect_to '/restaurants' unless request.xhr?
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper


end

app/helpers/reviews_helper.rb
module ReviewsHelper
  # place star_rating method here since it doesn't really have to do with the
  # base logic and is not strictly to do with looks
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)

    rounded_rating = rating.round
    remainder = 5 - rounded_rating
    ('★' * rounded_rating) + ('☆' * remainder)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<nav>
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <%= link_to('Edit details', edit_user_registration_path) %>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>  
    <%= link_to('Sign up', new_user_registration_path)  %>
  <% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>

  <div id="error-list">
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>

<% end %>

<%= form_for @restaurant do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :cuisine %>
  <%= f.text_field :cuisine, required: true %>

  <%= f.submit %>

<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to "Add new restaurant", new_restaurant_path %>

<br>

<% if @restaurants.any? %>
  <ul>
    <% @restaurants.each do |r| %>
      <li class="restaurant">
        <%= r.name %> (<%= r.cuisine %>) 
        <% if user_signed_in? %> ||
          <%= link_to "Review #{r.name}", new_restaurant_review_path(r.id) %> ||
          <%= link_to "Edit #{r.name}", edit_restaurant_path(r.id) %> ||
          <%= link_to "Delete #{r.name}", restaurant_path(r.id), method: :delete, "data-confirm" => 'Are you sure?' %> <br>
        <% end %>

        Average rating: 
        <span class="average_rating">
          <%= star_rating(r.average_rating) %>
        </span>
        
        <ul class="reviews">
          <% r.reviews.each do |review| %>
            <li>
              <%= review.thoughts %> (<%= star_rating(review.rating) %>)
            </li>
          <% end %>
        </ul>
        
        <% if user_signed_in? %>
          <%= form_for [r, @review] do |f| %>
            <%= f.label :thoughts %>
            <%= f.text_area :thoughts %>

            <%= f.label :rating %>
            <%= f.select :rating, 1..5 %>

            <%= f.submit %>
          <% end %>
        <% end %>

      </li>
    <% end %>
  </ul>
<% else %>
  There are no restaurants listed
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>

  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>

  <%= f.label :rating %>
  <%= f.select :rating, 1..5 %>

  <%= f.submit %>

<% end %>